[
    "1x2",
    "Double chance",
    "Handicap 1:0",
    "Handicap 0:1",
    "Handicap 0:2",
    "Handicap -1.5 / +1.5",
    "Handicap -0.5 / +0.5",
    "Handicap +0.5 / -0.5",
    "1st half - 1x2",
    "1st half - Double chance",
    "1st half - Handicap -0.5 / +0.5",
    "1st half - Handicap 0:1",
    "2nd half - 1x2",
    "2nd half - Double chance",
    "2nd half - Handicap -0.5 / +0.5",
    "Under/Over 0.5 goals",
    "Under/Over 1.5 goals",
    "Under/Over 2.5 goals",
    "Under/Over 3.5 goals",
    "Under/Over 4.5 goals",
    "Real Valladolid Under/Over 0.5 goals",
    "2nd half - Handicap 0:1",
    "Real Valladolid Under/Over 1.5 goals",
    "Real Valladolid Under/Over 2.5 goals",
    "CD Tenerife Under/Over 0.5 goals",
    "CD Tenerife Under/Over 1.5 goals",
    "CD Tenerife Under/Over 2.5 goals",
    "1st half - Under/Over 0.5 goals",
    "1st half - Under/Over 1.5 goals",
    "1st half - Under/Over 2.5 goals",
    "2nd half - Under/Over 0.5 goals",
    "2nd half - Under/Over 1.5 goals",
    "2nd half - Under/Over 2.5 goals",
    "1st half - Real Valladolid Under/Over 0.5",
    "1st half - Real Valladolid Under/Over 1.5",
    "1st half - Real Valladolid Under/Over 2.5",
    "1st half - CD Tenerife Under/Over 0.5",
    "1st half - CD Tenerife Under/Over 1.5",
    "2nd half - Real Valladolid Under/Over 0.5 goals",
    "2nd half - Real Valladolid Under/Over 1.5 goals",
    "2nd half - Real Valladolid Under/Over 2.5 goals",
    "2nd half - CD Tenerife Under/Over 0.5 goals",
    "2nd half - CD Tenerife Under/Over 1.5 goals",
    "2nd half - CD Tenerife Under/Over 2.5 goals",
    "Under 1.5 goals in both halves",
    "Over 1.5 goals in both halves",
    "Draw no bet",
    "1st half - Draw no bet",
    "2nd half - Draw no bet",
    "Real Valladolid will win - no bet",
    "CD Tenerife will win - no bet",
    "Both teams to score",
    "1st half - Both teams to score",
    "2nd half - Both teams to score",
    "1st/2nd half - Both teams to score",
    "Which team will score",
    "Any team to win",
    "Real Valladolid to win",
    "CD Tenerife to win",
    "Highest scoring half",
    "Real Valladolid highest scoring half",
    "CD Tenerife highest scoring half",
    "Halftime/Fulltime",
    "Correct score with Other",
    "1st half - Correct score",
    "2nd half - Correct score",
    "Halftime/Fulltime Correct score",
    "Multiscores",
    "Multigoals",
    "1st half - Multigoals",
    "2nd half - Multigoals",
    "Real Valladolid Multigoals",
    "CD Tenerife Multigoals",
    "Player to score first goal",
    "Player to score goal in the match",
    "Player to score last goal",
    "1st goal",
    "Last goal",
    "1st goal and 1x2",
    "1st half - 1st goal",
    "2nd half - 1st goal",
    "When will the 1st goal be scored (10 min interval)",
    "When will the 1st goal be scored (15 min interval)",
    "1x2 from 1 to 10 minute",
    "Goal range",
    "Exact goals",
    "1st half - Exact goals",
    "1st half - Exact goals",
    "2nd half - Exact goals",
    "Real Valladolid - Exact goals",
    "CD Tenerife - Exact goals",
    "Total goals - Odd/Even",
    "1st half - Odd/Even",
    "2nd half - Odd/Even",
    "Real Valladolid - Odd/Even",
    "CD Tenerife - Odd/Even",
    "1X2 and Under/Over 1.5 goals",
    "1X2 and Under/Over 2.5 goals",
    "1X2 and Under/Over 3.5 goals",
    "1X2 and Under/Over 4.5 goals",
    "1x2 and Both teams to score",
    "Both teams to score and Under/Over 2.5 goals",
    "Double chance and Under/Over 1.5 goals",
    "Double chance and Under/Over 2.5 goals",
    "Double chance and Under/Over 3.5 goals",
    "Double chance and Under/Over 4.5 goals",
    "Double chance and Both teams to score",
    "Double chance in match and Both teams score in 1st half",
    "Double chance in match and Both teams score in 2nd half",
    "1st half - 1x2 and Under/Over 1.5 goals",
    "2nd half - 1x2 and Under/Over 1.5 goals",
    "1st half - 1x2 and Both teams to score",
    "2nd half - 1x2 and Both teams to score",
    "1st half - Double chance and Both teams to score",
    "2nd half - Double chance and Both teams to score",
    "\tHalftime/fulltime and Under/Over 1.5 goals",
    "\tHalftime/fulltime and Under/Over 2.5 goals",
    "\tHalftime/fulltime and Under/Over 3.5 goals",
    "Halftime/fulltime and Under/Over 0.5 goals in 1st half",
    "Halftime/fulltime and Under/Over 1.5 goals in 1st half",
    "Halftime/fulltime and Under/Over 2.5 goals in 1st half",
    "Real Valladolid to win or Under 2.5 goals in match",
    "Draw or Under 2.5 goals in match",
    "CD Tenerife to win or Under 2.5 goals in match",
    "Real Valladolid to win or over 2.5 goals in match",
    "Draw or Over 2.5 goals in match",
    "CD Tenerife to win or Over 2.5 goals in match",
    "Real Valladolid to win or Both teams to score",
    "Draw or Both teams to score",
    "CD Tenerife to win or Both teams to score",
    "Real Valladolid to win or Any team clean sheet",
    "Draw or Any team clean sheet",
    "CD Tenerife to win or Any team clean sheet",
    "Real Valladolid to score in both halves",
    "CD Tenerife to score in both halves",
    "Real Valladolid to win both halves",
    "CD Tenerife to win both halves",
    "Real Valladolid to win either half",
    "CD Tenerife to win either half",
    "Real Valladolid win to nil",
    "CD Tenerife win to nil",
    "Real Valladolid clean sheet",
    "CD Tenerife clean sheet",
    "1st half - Real Valladolid clean sheet",
    "1st half - CD Tenerife clean sheet",
    "2nd half - Real Valladolid clean sheet",
    "2nd half - CD Tenerife clean sheet",
    "Winning margin"
]
